openapi: 3.0.1
info:
  description: Title
  title: Title
  version: 1.0.0
servers:
- url: https://www/api
paths:
  /:
    get:
      responses:
        "200":
          content: {}
          description: OK
      x-accepts: application/json
components:
  schemas: {}
x-original-swagger-version: "2.0"

